pluginManagement {
    repositories {
        //mavenLocal()
        //maven { url = '...' }
        gradlePluginPortal()
    }
}

buildCache {
    local {
        directory = new File(rootDir, 'build-cache')
    }
}

rootProject.name = 'AuthenticationMS'

include ':app-service'
include ':model'
include ':usecase'
project(':app-service').projectDir = file('./applications/app-service')
project(':model').projectDir = file('./domain/model')
project(':usecase').projectDir = file('./domain/usecase')
include ':reactive-web'
project(':reactive-web').projectDir = file('./infrastructure/entry-points/reactive-web')
include ':request-validator'
project(':request-validator').projectDir = file('./infrastructure/helpers/request-validator')
include ':r2dbc-mysql'
project(':r2dbc-mysql').projectDir = file('./infrastructure/driven-adapters/r2dbc-mysql')
include ':custom-mapper'
project(':custom-mapper').projectDir = file('./infrastructure/helpers/custom-mapper')
include ':logger'
project(':logger').projectDir = file('./infrastructure/helpers/logger')
include ':metrics'
project(':metrics').projectDir = file('./infrastructure/helpers/metrics')